apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage-infra-all
  description: Import all infrastructure catalog entities
spec:
  targets:
    - ./catalog/resources/*.yaml
    - ./catalog/applications/*.yaml
